const forms = require('@tailwindcss/forms');
const containerQueries = require('@tailwindcss/container-queries');

module.exports = {
  darkMode: 'class',
  content: [
    './public/templates/**/*.html',
    './public/templates/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        background: '#f9f9f9',
        card: '#ffffff',
        primary: '#a73a00',
        'primary-container': '#ff5c00',
        'primary-fixed': '#ffdbce',
        'primary-fixed-dim': '#ffb59a',
        'inverse-primary': '#ffb59a',
        'on-primary': '#ffffff',
        'on-primary-container': '#521800',
        'on-primary-fixed': '#370e00',
        'on-primary-fixed-variant': '#802a00',
        secondary: '#9d431b',
        'secondary-container': '#fe8c5f',
        'secondary-fixed': '#ffdbce',
        'secondary-fixed-dim': '#ffb59a',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#742500',
        'on-secondary-fixed': '#370e00',
        'on-secondary-fixed-variant': '#7e2c04',
        tertiary: '#0061a6',
        'tertiary-container': '#0096fd',
        'tertiary-fixed': '#d2e4ff',
        'tertiary-fixed-dim': '#a0c9ff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#002d51',
        'on-tertiary-fixed': '#001c37',
        'on-tertiary-fixed-variant': '#00497f',
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'on-surface': '#1b1b1b',
        'on-surface-variant': '#5b4137',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f1f1f1',
        outline: '#8f7065',
        'outline-variant': '#e4beb1',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Manrope', 'Inter', 'sans-serif'],
        headline: ['Manrope', 'Inter', 'sans-serif'],
        body: ['Manrope', 'Inter', 'sans-serif'],
        label: ['Manrope', 'Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [forms, containerQueries],
};
